### ISSUE TITLE
Description check

### ISSUE THREAD

**Issue by leslieperez** [pabloOnate/iraceplot#1]
Revisar como definir autores y mantenedor en DESCRIPTION

**Comment by MLopez-Ibanez** [comment]
See https://github.com/MLopez-Ibanez/irace/blob/master/DESCRIPTION

**Comment by pabloOnate** [comment]
En el siguiente enlace, dice que es seguro ignorar este mensaje de Note, ya que se produce como un recordatorio

https://stackoverflow.com/questions/23829978/checking-cran-incoming-feasibility-note-maintainer
