### ISSUE TITLE
las dos opciones hacen lo mismo

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#11]
https://github.com/pabloOnate/iraceplot/blob/4dc6f5b8a92b2c2958a270d84657033d2b352bd2/R/boxplot_test.R#L149-L153

Quizás:

```R
  if (type == "all" || type == "ibest) {
      p <- p + facet_grid(cols = vars(datos$iteration_f), scales = "free")
  }
```

**Comment by pabloOnate** [comment]
He realizado el cambio correspondiente
Muchas gracias.

**Comment by MLopez-Ibanez** [comment]
Gracias a ti pero no veo el cambio. ¿Quizás tienes que hacer push?

Si escribes en el mensaje de git  "Fix #11 ...", el commit aparece en este issue.

**Comment by pabloOnate** [comment]
Si, antes no había realizado el push correspondiente
