### ISSUE TITLE
Algunos plots no se muestran en el vignette

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#13]
Screenshot: 

![image](https://user-images.githubusercontent.com/2620021/118005932-bcb31b00-b342-11eb-8aa2-c71f8da376bd.png)

**Comment by pabloOnate** [comment]
Si, los tengo comentados de momento, por sus tiempos de demora la creación del grafico al momento de hacer los check.

**Comment by MLopez-Ibanez** [comment]
> Si, los tengo comentados de momento, por sus tiempos de demora la creación del grafico al momento de hacer los check.

OK. Pero nota que en markdown, los comentarios se escriben con 

```markdown
<!-- Comentario -->
```
no con:
```markdown
# Esto no es un comentario
```
