### ISSUE TITLE
Error: processing vignette 'iraceplot_package.Rmd' failed with diagnostics: invalid 'path' argument

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#14]
https://github.com/pabloOnate/iraceplot/runs/2581525128

Error: --- re-building ‘iraceplot_package.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
Quitting from lines 140-141 (iraceplot_package.Rmd) 
Error: Error: processing vignette 'iraceplot_package.Rmd' failed with diagnostics:
invalid 'path' argument

**Comment by pabloOnate** [comment]
Arreglado
