### ISSUE TITLE
Github action: install pandoc

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#15]
Currently, R-cmd-check fails: https://github.com/pabloOnate/iraceplot/runs/2646389728

You need to setup pandoc in :

https://github.com/pabloOnate/iraceplot/blob/master/.github/workflows/R-CMD-check.yaml

Something like:
```
uses: r-lib/actions/setup-pandoc@v1
```

**Comment by pabloOnate** [comment]
Agregado
Muchas gracias Manuel
