### ISSUE TITLE
'markdown' package should appear in 'Suggests'

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#2]
Error: --- re-building ‘iraceplot_package.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
Error: Error: processing vignette 'iraceplot_package.Rmd' failed with diagnostics:
Error: Error in proc$get_built_file() : Build process failed
The 'markdown' package should be installed and declared as a dependency of the 'iraceplot' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
--- failed re-building ‘iraceplot_package.Rmd’
Execution halted

**Comment by pabloOnate** [comment]
Arreglado
