### ISSUE TITLE
Ejemplo adicional

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#20]
https://pabloonate.github.io/iraceplot/reference/boxplot_test.html

"Logical (default TRUE) to fit through an equation of minimum percentage distance between the values of each row of all configurations"

Creo que quieres decir: "Instead of raw solution cost, show relative percentage deviation from the best of each iteration" 

Añadir un ejemplo que use rpd=FALSE para que se vea la diferencia.

**Comment by leslieperez** [comment]
Se agregó un ejemplo utilizando rpd=FALSE y se ajustó el texto del la documentación.
