### ISSUE TITLE
Namespace in Imports field not imported from: ‘webshot’

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#3]
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘webshot’
  All declared Imports should be used.
Unexported object imported by a ':::' call: ‘irace:::path.rel2abs’
  See the note in ?`:::` about the use of this operator.

**Comment by pabloOnate** [comment]
Se arregla creando la función en el propio paquete, para no depender del paquete irace

**Comment by MLopez-Ibanez** [comment]
Hola Pablo,

Creo que sería mejor exportar la función desde irace. 

Dejemos tu solución por ahora para arreglar el NOTE, pero voy a cambiar irace para exportar la función y que se pueda usar. Si ves otras funciones de irace que se puedan usar en vez de duplicar, dímelo

Saludos, Manuel

**Comment by pabloOnate** [comment]
Hola Manuel,
En este caso hice una replica de la función, ya que fue la conclusión que llegamos con la profesora Leslie, pero le avisare si es necesario usar otras funciones para exportar.
Saludos.
