### ISSUE TITLE
replace pdf()+plot() wiht ggsave()

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#4]
Rather than save files using pdf() + plot() like here:

https://github.com/pabloOnate/iraceplot/blob/4dc6f5b8a92b2c2958a270d84657033d2b352bd2/R/boxplot_training.R#L106

It would be better to use https://ggplot2.tidyverse.org/reference/ggsave.html

**Comment by pabloOnate** [comment]
Se ha reemplazado en los casos que se necesite solo guardar un grafico por ggsave()
En otros casos donde se van guardando varios gráficos en el mismo pdf se mantiene el uso de pdf() + plot + dev.off() por su flexibilidad y ggsave() no permite el guardado iterativo en un solo pdf.
