### ISSUE TITLE
check also with --as-cran

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#7]
See use_github_action_check_standard

https://usethis.r-lib.org/reference/use_github_action.html

Example: https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml

**Comment by MLopez-Ibanez** [comment]
Otro ejemplo: https://github.com/mrbarrientosg/iraceStudio/blob/master/.github/workflows/R-CMD-check.yaml

**Comment by pabloOnate** [comment]
Se hacen las modificaciones correspondientes
