### ISSUE TITLE
crear automáticamente una página web con pkgdown

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pabloOnate/iraceplot#8]
https://usethis.r-lib.org/reference/use_pkgdown.html
and
https://pkgdown.r-lib.org/articles/pkgdown.html#configuration

Esto sirve como un test adicional, ya que uno puede rápidamente ver la salida de los ejemplos y detectar si algo se rompió.

Ejemplo: https://mlopez-ibanez.github.io/irace/

**Comment by pabloOnate** [comment]
Manuel, ya se subieron los cambios referente a la creación de la pagina, esto todavía esta en una etapa de cambios que hemos estado revisando con la profesora Leslie, pero avisar que ya esta una etapa inicial de esta, aquí le dejo el link de la pagina:
https://pabloonate.github.io/iraceplot/

**Comment by MLopez-Ibanez** [comment]
Hola Pablo, muy buena la página! Estupendo trabajo!

**Comment by MLopez-Ibanez** [comment]
Te sugeriría que editaras la descripción del repositorio en github para incluir la URL: https://pabloonate.github.io/iraceplot/
Así aparece en la columna de texto de la derecha en github bajo "About".

**Comment by pabloOnate** [comment]
Agregado

**Comment by leslieperez** [comment]
Cierro este issue ya que esta agregado el sitio.
